### ISSUE TITLE
Suspicious AF

### ISSUE THREAD

**Issue by smithb895** [GameFusionNetWork/PakExplorer2.0#1]
No one download this until they post the actual source code.   The binary they link has multiple flags on VT:  https://www.virustotal.com/gui/file/856b7dc2f5d208dac0bed323aa69b231f026075d572abdaa08a4527552e6d0f9?nocache=1

**Comment by GameFusionNetWork** [comment]
Then dont use it. I took flipperz original project and updated it to support every file type within a pak file. Not every software you use will be open source, the only reason its not, Is because I added a token system and a new python gui. No one is forcing you to download it.
